#remote_theme: pages-themes/minimal@v0.2.0
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache

include: ["_pages"]
#title: "V Congreso Iberoamericano de Investigación en Conservación del Patrimonio"
#subtitle: "ICP 2024"

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-x"
      url: "https://twitter.com/clioviz"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/ClioViz/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/clioviz/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCWGHwvW7nhxWyKco1wtmYhw"

logo: "assets/images/LogoCV.png"

masthead_title: "Proyecto ClioViz"
